@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYnJ1bm8uY2hhZ2FzQGdtYWlsLmNvbSIsImlhdCI6MTc3NDQ3MDE5MiwiZXhwIjoxNzc0NDczNzkyfQ.joTotCt4McU43n3Phe2zmBRJaTpjlhgLWy7CWexV2L0

###
//SERVIDOR DE TESTE, PARA VER SE ESTÁ ON!
GET http://localhost:3001/health HTTP/1.1

////////////////////////////////////////////////////////

###
//CRIA USUARIO
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Pedro",
  "email": "pedro@gmail.com",
  "password": "pedro",
  "role": "DEFAULT"
}

///////////////// PRECISA DO TOKEN /////////////////// 

###
//LOGIN
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "bruno.chagas@gmail.com",
    "password": "sua_senha_aqui"
}

###
//MOSTRA TODOS OS USUARIOS
GET http://localhost:3001/users HTTP/1.1
Authorization: Bearer {{token}}

###
//BUSCA PELO USUARIO PELO ID
GET http://localhost:3001/users/1 HTTP/1.1
Authorization: Bearer {{token}}

###
//LOGIN
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "arthur.sausen@gmail.com",
    "password": "arthur123"
}

###
GET  http://localhost:3001/users
Authorization: Bearer {{token}}

###
GET  http://localhost:3001/posts
Authorization: Bearer {{token}}

###
//LOGIN
POST http://localhost:3001/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "post arthur",
    "title": "arthur123"
}

//////////////  PARTE ADMIN  /////////////
###
GET http://localhost:3001/admin
Authorization: Bearer {{token}}